version: "3"
services:
  frontend:
    image: jangdm37/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
  nginx:
    restart: always
    image: jangdm37/nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend
  backend:
    image: jangdm37/docker-backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
